apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: brzina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: brzina-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgres://admin:changeme@postgres.brzina.svc.cluster.local:5432/brzina
