replicaCount: 1
image:
  repository: r2limptl.eu-south-mil.container-registry.ovh.net/brzina-images/brzina-api
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
env:
  DATABASE_URL: "postgresql+asyncpg://brzina_user:changeme@brzina-postgres:5432/brzina"
  AUTH_SERVICE_URL: "http://brzina-auth:8000"
  CAR_SERVICE_URL: "http://brzina-car:8000"
  BOOKING_SERVICE_URL: "http://brzina-booking:8000"
  PAYMENT_SERVICE_URL: "http://brzina-payment:8000"
