replicaCount: 1
image:
  repository: brzina-payment
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
env:
  DATABASE_URL: "postgres://brzina_user:changeme@postgres.brzina.svc.cluster.local:5432/brzina"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
