apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "nginx-ingress.fullname" . }}-admission
  labels:
    app.kubernetes.io/name: {{ include "nginx-ingress.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
webhooks:
  - name: validate.nginx.ingress.kubernetes.io
    rules:
      - apiGroups: ["networking.k8s.io"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["ingresses"]
        scope: "Namespaced"
    clientConfig:
      service:
        name: {{ include "nginx-ingress.fullname" . }}-controller
        namespace: {{ .Release.Namespace }}
        path: /networking/v1/ingresses
      caBundle: ""
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 10
