apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-ingress.fullname" . }}-controller
  labels:
    app.kubernetes.io/name: {{ include "nginx-ingress.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  # Custom NGINX configuration can be added here
