replicaCount: 1
image:
  repository: grafana/grafana
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
resources: {}
prometheus:
  serviceName: prometheus
  servicePort: 9090

ingress:
  enabled: true
  host: grafana.local
