apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brzina-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: {{ .Values.frontendPath }}(.*)
            pathType: Prefix
            backend:
              service:
                name: brzina-frontend
                port:
                  number: 80
          - path: {{ .Values.apiPath }}(.*)
            pathType: Prefix
            backend:
              service:
                name: brzina-api
                port:
                  number: 8000
