replicaCount: 1
image:
  repository: r2limptl.eu-south-mil.container-registry.ovh.net/brzina-images/brzina-car
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
env:
  DATABASE_URL: "postgresql+asyncpg://brzina_user:changeme@brzina-postgres:5432/brzina"
