apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: carshare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: carshare-auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: SERVICE_NAME
              value: auth-service
            - name: DATABASE_URL
              value: postgres://carshare_user:changeme@postgres.carshare.svc.cluster.local:5432/carshare
            - name: JWT_SECRET
              value: supersecret
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000