apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: carshare
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 8000
      targetPort: 8000
      name: http