apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'api'
        static_configs:
          - targets: ['brzina-api:8000']
      - job_name: 'auth'
        static_configs:
          - targets: ['brzina-auth:8000']
      - job_name: 'booking'
        static_configs:
          - targets: ['brzina-booking:8000']
      - job_name: 'car'
        static_configs:
          - targets: ['brzina-car:8000']
      - job_name: 'payment'
        static_configs:
          - targets: ['brzina-payment:8000']
      - job_name: 'template'
        static_configs:
          - targets: ['brzina-template:8000']
