apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "car.fullname" . }}
  labels:
    app: {{ include "car.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "car.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "car.name" . }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: car
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | quote }}

          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 60
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 5
